on: [push]

jobs:
  update_wakatime_image:
    runs-on: ubuntu-latest
    name: Save tjv dataset to repo
    steps:
      # This is required to use the git-auto-commit-action
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          
      # Load current date
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time
        
      # Display current time
      #- name: Use current time
      #  env:
      #    TIME: "${{ steps.current-time.outputs.time }}"
      #  run: echo $TIME

      # Load and cache the image
      - name: Save tjv csv snapshot to my repo
        uses: Minituff/save-image@v1.3
        id: wakatime
        with:
          url: 'http://tjv.pristupinfo.hr/?sort=1&page=1&download'
          imagePath: 'tjv-datasets/tjv-snapshot-${{ steps.current-time.outputs.time }}.csv'
          #requiredContentType: 'text/csv'

      # If you do not commit the changes, then the action does not work
      - name: "Commit changes if necessary"
        uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          commit_message: Adds tjv csv snapshot
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: Author <github-actions[bot]@users.noreply.github.com>
  
